on:
  push:
    branches: [main, dev]
  pull_request:

name: valgrind

jobs:
  cargo-valgrind:
    name: Run valgrind
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust:
          # 1.83 causes cargo-valgrind
          # to fail, so we pin until that
          # gets resolved
          - 1.82.0
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update -y
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt-get install -y valgrind
        if: matrix.os == 'ubuntu-latest'
      - run: cargo install cargo-valgrind
      - name: run cargo valgrind on demes::ffi
        run: |
            cargo valgrind test --manifest-path demes/Cargo.toml --all-features ffi
      - name: run cargo valgrind on demes_forward_capi
        run: |
            cargo valgrind test --manifest-path demes-forward-capi/Cargo.toml --all-features

